<?
require_once("classUtil.php");
require_once("classUsuario.php");
require_once("classPassaro.php");
require_once("classEspecie.php");
require_once("classMuda.php");
require_once("classAcasalamento.php");
require_once("classCriadouro.php");
require_once("classCliente.php");
require_once("classVenda.php");
require_once("classMorte.php");
?>